from datetime import datetime, UTC

from sqlalchemy import Integer, String, DateTime, UniqueConstraint, Text, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, relationship, mapped_column


class Base(DeclarativeBase):
    pass


class ImageIndex(Base):
    __tablename__ = "image_index"
    __table_args__ = (
        UniqueConstraint(
            "image_hash",
            "embedding_model",
            name="uq_image_hash_embedding_model"
        ),
        {
            "comment": "Vector index of images used for similarity search in RAG pipeline"
        }
    )
    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for RAG image index"
    )
    external_photo_id: Mapped[str] = mapped_column(
        String,
        unique=True,
        index=True,
        nullable=False,
        comment="External photo id form vector-collector-service for RAG image index"
    )
    file_storage_uri: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="File path for RAG image index, same for vector-collector-service, 640 size photos"
    )
    image_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Image hash for RAG image index"
    )
    embedding_model: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Embedding model name for RAG image index"
    )
    vector_status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="PENDING",
        comment="Vector status for RAG image index, statuses: PENDING, VECTORIZED, FAILED"
    )
    meta_data: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Meta data for RAG image index. MODEL, BRAND, TYPE, YEAR, COLOR"
    )
    recognition_candidates: Mapped[list[RecognitionCandidate]] = relationship(
        "RecognitionCandidate",
        back_populates="image"
    )
    similarity_matches: Mapped[list[SimilarityMatch]] = relationship(
        "SimilarityMatch",
        foreign_keys="[SimilarityMatch.image_index_id]",
        back_populates="image"
    )
    recognition_state: Mapped["RecognitionState"] = relationship(
        back_populates="image",
        uselist=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
    )


class RecognitionState(Base):
    __tablename__ = "recognition_state"
    __table_args__ = {
        "comment": "Processing state of recognition pipeline for a given image index entry"
    }

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for recognition state record"
    )

    image_index_id: Mapped[int] = mapped_column(
        ForeignKey("image_index.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        comment="Reference to image_index entry"
    )

    analysis_status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="RECEIVED",
        comment="Status of analysis pipeline: RECEIVED, PROCESSING, DONE, FAILED"
    )

    suggestion_status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="NONE",
        comment="Status of recognition suggestion: NONE, UNKNOWN, SUGGESTED"
    )

    verification_status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="UNVERIFIED",
        comment="Human verification status: UNVERIFIED, PENDING_REVIEW, VERIFIED, REJECTED"
    )

    last_error: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Last error message produced during recognition pipeline"
    )

    image: Mapped[ImageIndex] = relationship(
        "ImageIndex",
        uselist=False,
        back_populates="recognition_state"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
        comment="Timestamp when recognition state was created"
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
        comment="Timestamp when recognition state was last updated"
    )


class RecognitionCandidate(Base):
    __tablename__ = "recognition_candidates"
    __table_args__ = {
        "comment": "Recognition candidates generated by similarity search, external LLM or manual review"
    }
    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for recognition candidate"
    )
    image_index_id: Mapped[int] = mapped_column(
        ForeignKey("image_index.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Reference to image_index entry"
    )
    source: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="Source of candidate: similarity, external_llm, manual"
    )
    candidate_brand: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Suggested brand of object detected in image"
    )
    candidate_model: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Suggested model of object detected in image"
    )
    candidate_color: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Suggested color of object detected in image"
    )
    candidate_type: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Suggested type/category of object detected in image"
    )
    candidate_year: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Suggested production year of object detected in image"
    )
    confidence: Mapped[float | None] = mapped_column(
        nullable=True,
        comment="Confidence score for this candidate suggestion"
    )
    is_selected: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
        comment="Indicates if this candidate was selected as final recognition result"
    )
    image: Mapped[ImageIndex] = relationship(
        "ImageIndex",
        uselist=False,
        back_populates="recognition_candidates"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
        comment="Timestamp when candidate suggestion was created"
    )


class SimilarityMatch(Base):
    __tablename__ = "similarity_matches"
    __table_args__ = {
        "comment": "Similarity search matches between images in vector index"
    }

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for similarity match entry"
    )

    image_index_id: Mapped[int] = mapped_column(
        ForeignKey("image_index.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Source image index entry used for similarity search"
    )

    matched_image_index_id: Mapped[int] = mapped_column(
        ForeignKey("image_index.id", ondelete="CASCADE"),
        nullable=False,
        comment="Image index entry that was matched as similar"
    )

    similarity_score: Mapped[float] = mapped_column(
        nullable=False,
        comment="Vector similarity score between images"
    )

    rank: Mapped[int] = mapped_column(
        nullable=False,
        comment="Ranking position of match (1 = most similar)"
    )
    image: Mapped[ImageIndex] = relationship(
        "ImageIndex",
        uselist=False,
        foreign_keys=[image_index_id],
        back_populates="similarity_matches"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(UTC),
        nullable=False,
        comment="Timestamp when similarity match was computed"
    )
